import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import "../../styles/navbar.css"
import React from "react";
import {CartProvider} from "@/context/CartContext";
import {ThemeProvider} from "next-themes";
import {NextUIProvider} from "@nextui-org/react";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (

        <html lang="en">
        <body className={inter.className}>
        <CartProvider>
            <ThemeProvider attribute={'class'} defaultTheme={'light'} themes={["light", "dark"]} enableSystem={false}>
                <NextUIProvider>
                    {children}
                </NextUIProvider>
            </ThemeProvider>
        </CartProvider>

        </body>
        </html>

    );
}
